<template>
    <div>
        <TheHeader></TheHeader>
        <ServicesRental></ServicesRental>
        <TheEngineer></TheEngineer>
        <TheRental></TheRental>
        <the-footer></the-footer>
    </div>
</template>